### ISSUE TITLE
Errors after install 

### ISSUE THREAD

**Issue by Pablo2m** [waartaa/waartaa#27] opened 2014-01-13 12:52 UTC
Can you help me?
SO Fedora 20 

Traceback: 

[pablo2m@localhost waartaa]$ ./setup.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0Downloading Meteor distribution
100  4223    0  4223    0     0   2432      0 --:--:--  0:00:01 --:--:--  2434
###### #################################################################  100,0%

Meteor 0.7.0.1 has been installed in your home directory (~/.meteor).
Writing a launcher script to /usr/local/bin/meteor for your convenience.
This may prompt for your password.

To get started fast:

  $ meteor create ~/my_cool_app
  $ cd ~/my_cool_app
  $ meteor

Or see the docs at:

  docs.meteor.com

npm http GET https://registry.npmjs.org/meteorite
npm http 200 https://registry.npmjs.org/meteorite
npm http GET https://registry.npmjs.org/meteorite/-/meteorite-0.7.1.tgz
npm http 200 https://registry.npmjs.org/meteorite/-/meteorite-0.7.1.tgz
npm http GET https://registry.npmjs.org/ddp
npm http GET https://registry.npmjs.org/underscore/1.3.3
npm http GET https://registry.npmjs.org/fstream
npm http GET https://registry.npmjs.org/wrench
npm http GET https://registry.npmjs.org/optimist
npm http GET https://registry.npmjs.org/prompt/0.2.11
npm http GET https://registry.npmjs.org/colors/0.6.0-1
npm http GET https://registry.npmjs.org/async/0.2.9
npm http 200 https://registry.npmjs.org/underscore/1.3.3
npm http GET https://registry.npmjs.org/underscore/-/underscore-1.3.3.tgz
npm http 200 https://registry.npmjs.org/prompt/0.2.11
npm http GET https://registry.npmjs.org/prompt/-/prompt-0.2.11.tgz
npm http 200 https://registry.npmjs.org/wrench
npm http GET https://registry.npmjs.org/wrench/-/wrench-1.5.4.tgz
npm http 200 https://registry.npmjs.org/colors/0.6.0-1
npm http GET https://registry.npmjs.org/colors/-/colors-0.6.0-1.tgz
npm http 200 https://registry.npmjs.org/ddp
npm http GET https://registry.npmjs.org/ddp/-/ddp-0.4.3.tgz
npm http 200 https://registry.npmjs.org/underscore/-/underscore-1.3.3.tgz
npm http 200 https://registry.npmjs.org/optimist
npm http GET https://registry.npmjs.org/optimist/-/optimist-0.6.0.tgz
npm http 200 https://registry.npmjs.org/async/0.2.9
npm http GET https://registry.npmjs.org/async/-/async-0.2.9.tgz
npm http 200 https://registry.npmjs.org/fstream
npm http GET https://registry.npmjs.org/fstream/-/fstream-0.1.25.tgz
npm http 200 https://registry.npmjs.org/prompt/-/prompt-0.2.11.tgz
npm http 200 https://registry.npmjs.org/colors/-/colors-0.6.0-1.tgz
npm http 200 https://registry.npmjs.org/wrench/-/wrench-1.5.4.tgz
npm http 200 https://registry.npmjs.org/ddp/-/ddp-0.4.3.tgz
npm http 200 https://registry.npmjs.org/optimist/-/optimist-0.6.0.tgz
npm http 200 https://registry.npmjs.org/async/-/async-0.2.9.tgz
npm http 200 https://registry.npmjs.org/fstream/-/fstream-0.1.25.tgz
npm http GET https://registry.npmjs.org/faye-websocket
npm http GET https://registry.npmjs.org/meteor-ejson
npm http GET https://registry.npmjs.org/node-srp
npm http GET https://registry.npmjs.org/rimraf
npm http GET https://registry.npmjs.org/mkdirp
npm http GET https://registry.npmjs.org/inherits
npm http GET https://registry.npmjs.org/graceful-fs
npm http GET https://registry.npmjs.org/wordwrap
npm http GET https://registry.npmjs.org/minimist
npm http GET https://registry.npmjs.org/pkginfo
npm http GET https://registry.npmjs.org/read
npm http GET https://registry.npmjs.org/utile
npm http GET https://registry.npmjs.org/revalidator
npm http GET https://registry.npmjs.org/winston
npm http 200 https://registry.npmjs.org/node-srp
npm http GET https://registry.npmjs.org/node-srp/-/node-srp-0.0.1.tgz
npm http 200 https://registry.npmjs.org/meteor-ejson
npm http GET https://registry.npmjs.org/meteor-ejson/-/meteor-ejson-0.6.3.tgz
npm http 200 https://registry.npmjs.org/inherits
npm http GET https://registry.npmjs.org/inherits/-/inherits-2.0.1.tgz
npm http 200 https://registry.npmjs.org/wordwrap
npm http GET https://registry.npmjs.org/wordwrap/-/wordwrap-0.0.2.tgz
npm http 200 https://registry.npmjs.org/mkdirp
npm http GET https://registry.npmjs.org/mkdirp/-/mkdirp-0.3.5.tgz
npm http 200 https://registry.npmjs.org/graceful-fs
npm http GET https://registry.npmjs.org/graceful-fs/-/graceful-fs-2.0.1.tgz
npm http 200 https://registry.npmjs.org/pkginfo
npm http GET https://registry.npmjs.org/pkginfo/-/pkginfo-0.3.0.tgz
npm http 200 https://registry.npmjs.org/node-srp/-/node-srp-0.0.1.tgz
npm http 200 https://registry.npmjs.org/read
npm http GET https://registry.npmjs.org/read/-/read-1.0.5.tgz
npm http 200 https://registry.npmjs.org/meteor-ejson/-/meteor-ejson-0.6.3.tgz
npm http 200 https://registry.npmjs.org/inherits/-/inherits-2.0.1.tgz
npm http 200 https://registry.npmjs.org/graceful-fs/-/graceful-fs-2.0.1.tgz
npm http 200 https://registry.npmjs.org/pkginfo/-/pkginfo-0.3.0.tgz
npm http 200 https://registry.npmjs.org/read/-/read-1.0.5.tgz
npm http 200 https://registry.npmjs.org/revalidator
npm http GET https://registry.npmjs.org/revalidator/-/revalidator-0.1.6.tgz
npm http 200 https://registry.npmjs.org/mkdirp/-/mkdirp-0.3.5.tgz
npm http 200 https://registry.npmjs.org/utile
npm http GET https://registry.npmjs.org/utile/-/utile-0.2.1.tgz
npm http 200 https://registry.npmjs.org/minimist
npm http GET https://registry.npmjs.org/minimist/-/minimist-0.0.5.tgz
npm http 200 https://registry.npmjs.org/rimraf
npm http GET https://registry.npmjs.org/rimraf/-/rimraf-2.2.5.tgz
npm http 200 https://registry.npmjs.org/wordwrap/-/wordwrap-0.0.2.tgz
npm http 200 https://registry.npmjs.org/revalidator/-/revalidator-0.1.6.tgz
npm http 200 https://registry.npmjs.org/utile/-/utile-0.2.1.tgz
npm http 200 https://registry.npmjs.org/faye-websocket
npm http GET https://registry.npmjs.org/faye-websocket/-/faye-websocket-0.7.2.tgz
npm http 200 https://registry.npmjs.org/minimist/-/minimist-0.0.5.tgz
npm http 200 https://registry.npmjs.org/rimraf/-/rimraf-2.2.5.tgz
npm http 200 https://registry.npmjs.org/faye-websocket/-/faye-websocket-0.7.2.tgz
npm http GET https://registry.npmjs.org/underscore
npm http GET https://registry.npmjs.org/underscore
npm http GET https://registry.npmjs.org/websocket-driver
npm http 200 https://registry.npmjs.org/winston
npm http GET https://registry.npmjs.org/winston/-/winston-0.6.2.tgz
npm http 200 https://registry.npmjs.org/underscore
npm http GET https://registry.npmjs.org/underscore/-/underscore-1.4.4.tgz
npm http 200 https://registry.npmjs.org/underscore
npm http 200 https://registry.npmjs.org/websocket-driver
npm http GET https://registry.npmjs.org/websocket-driver/-/websocket-driver-0.3.2.tgz
npm http 200 https://registry.npmjs.org/winston/-/winston-0.6.2.tgz
npm http 200 https://registry.npmjs.org/underscore/-/underscore-1.4.4.tgz
npm http 200 https://registry.npmjs.org/websocket-driver/-/websocket-driver-0.3.2.tgz
npm http GET https://registry.npmjs.org/mute-stream
npm http GET https://registry.npmjs.org/deep-equal
npm http GET https://registry.npmjs.org/i
npm http GET https://registry.npmjs.org/ncp
npm http GET https://registry.npmjs.org/mkdirp
npm http GET https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/cycle
npm http GET https://registry.npmjs.org/eyes
npm http GET https://registry.npmjs.org/request
npm http GET https://registry.npmjs.org/stack-trace
npm http GET https://registry.npmjs.org/pkginfo/-/pkginfo-0.2.3.tgz
npm http 200 https://registry.npmjs.org/mute-stream
npm http GET https://registry.npmjs.org/mute-stream/-/mute-stream-0.0.4.tgz
npm http 200 https://registry.npmjs.org/deep-equal
npm http GET https://registry.npmjs.org/deep-equal/-/deep-equal-0.1.2.tgz
npm http 304 https://registry.npmjs.org/mkdirp
npm http 200 https://registry.npmjs.org/cycle
npm http GET https://registry.npmjs.org/cycle/-/cycle-1.0.3.tgz
npm http 200 https://registry.npmjs.org/i
npm http GET https://registry.npmjs.org/i/-/i-0.3.2.tgz
npm http 200 https://registry.npmjs.org/pkginfo/-/pkginfo-0.2.3.tgz
npm http 200 https://registry.npmjs.org/ncp
npm http GET https://registry.npmjs.org/ncp/-/ncp-0.4.2.tgz
npm http 200 https://registry.npmjs.org/eyes
npm http GET https://registry.npmjs.org/eyes/-/eyes-0.1.8.tgz
npm http 200 https://registry.npmjs.org/stack-trace
npm http GET https://registry.npmjs.org/stack-trace/-/stack-trace-0.0.7.tgz
npm http 200 https://registry.npmjs.org/deep-equal/-/deep-equal-0.1.2.tgz
npm http 200 https://registry.npmjs.org/eyes/-/eyes-0.1.8.tgz
npm http 200 https://registry.npmjs.org/mute-stream/-/mute-stream-0.0.4.tgz
npm http 200 https://registry.npmjs.org/ncp/-/ncp-0.4.2.tgz
npm http 200 https://registry.npmjs.org/stack-trace/-/stack-trace-0.0.7.tgz
npm http 200 https://registry.npmjs.org/cycle/-/cycle-1.0.3.tgz
npm http 200 https://registry.npmjs.org/i/-/i-0.3.2.tgz
npm http 200 https://registry.npmjs.org/request
npm http GET https://registry.npmjs.org/request/-/request-2.9.203.tgz
npm http 200 https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/async/-/async-0.1.22.tgz
npm http 200 https://registry.npmjs.org/request/-/request-2.9.203.tgz
npm http 200 https://registry.npmjs.org/async/-/async-0.1.22.tgz
/bin/mrt -> /lib/node_modules/meteorite/bin/mrt.js

> meteorite@0.7.1 postinstall /lib/node_modules/meteorite
> sh ./completions/postinstall.sh

npm WARN unmet dependency /lib/node_modules/block-stream requires inherits@'~2.0.0' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
npm WARN unmet dependency /lib/node_modules/fstream requires inherits@'~2.0.0' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
npm WARN unmet dependency /lib/node_modules/fstream-ignore requires inherits@'2' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
npm WARN unmet dependency /lib/node_modules/fstream-npm requires inherits@'2' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
npm WARN unmet dependency /lib/node_modules/glob requires inherits@'2' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
npm WARN unmet dependency /lib/node_modules/npmconf requires inherits@'~2.0.0' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
npm WARN unmet dependency /lib/node_modules/tar requires inherits@'2' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
meteorite@0.7.1 /lib/node_modules/meteorite
├── colors@0.6.0-1
├── async@0.2.9
├── wrench@1.5.4
├── underscore@1.3.3
├── optimist@0.6.0 (wordwrap@0.0.2, minimist@0.0.5)
├── fstream@0.1.25 (inherits@2.0.1, graceful-fs@2.0.1, rimraf@2.2.5, mkdirp@0.3.5)
├── ddp@0.4.3 (faye-websocket@0.7.2, node-srp@0.0.1, meteor-ejson@0.6.3)
└── prompt@0.2.11 (revalidator@0.1.6, pkginfo@0.3.0, read@1.0.5, utile@0.2.1, winston@0.6.2)
✓ jquery-ui-bootstrap
    tag: https://github.com/TimHeckel/meteor-jquery-ui-bootstrap.git#v0.1.2
✓ observatory
    tag: https://github.com/jhoxray/observatory.git#v0.3.21
✓ irc
    tag: https://github.com/Pent/meteor-irc.git#v0.2.2
✓ handlebar-helpers
    tag: https://github.com/raix/Meteor-handlebar-helpers.git#v0.0.9
✓ require
    tag: https://github.com/tomconnors/meteor-require.git#v0.1.0
✓ presence
    tag: https://github.com/tmeasday/meteor-presence.git#v0.3.0
✓ bootstrap-3
    tag: https://github.com/mangasocial/meteor-bootstrap-3.git#v0.3.7
✓ accounts-ui-bootstrap-3
    tag: https://github.com/mangasocial/meteor-accounts-ui-bootstrap-3.git#v0.2.4
✓ nodetime
    tag: https://github.com/subhog/meteor-nodetime.git#v0.2.0
✓ moment
    tag: https://github.com/acreeger/meteor-moment.git#v2.2.1
✓ winston-loggly
    tag: https://github.com/tomrogers3/meteor-winston-loggly.git#v0.0.3
✓ winston
    tag: https://github.com/tomrogers3/meteor-winston.git#v0.0.3
✓ assert
    tag: https://github.com/peerlibrary/meteor-assert.git#v0.2.2
✓ nprogress
    tag: https://github.com/zhouzhuojie/meteor-nprogress.git#v0.0.3
✓ GAnalytics
    tag: https://github.com/datariot/meteor-ganalytics.git#v0.1.0
✓ jquery-ui
    tag: https://github.com/TimHeckel/meteor-jquery-ui.git#v1.9.2
✓ observatory-apollo
    tag: https://github.com/superstringsoftware/observatory-apollo.git#v0.3.2
✓ observatory-galileo
    branch: https://github.com/superstringsoftware/observatory-galileo.git#master

Done installing smart packages
[pablo2m@localhost waartaa]$  cd waartaa
[pablo2m@localhost waartaa]$ meteor
[[[[[ ~/waartaa/waartaa ]]]]]

Initializing mongo database... this may take a moment.
nodetime: updating npm dependencies -- nodetime...
winston-loggly: updating npm dependencies -- winston, winston-loggly...
winston: updating npm dependencies -- winston...
=> Errors prevented startup:

While building the application:
error: no such package: 'router'
error: no such package: 'HTML5-History-API'
error: no such package: 'page-js-ie-support'

=> Your application has errors. Waiting for file change.

**Comment by rtnpro** [comment] 2014-01-13 13:16
Thanks @Pablo2m for dropping by and reporting this issue. We're looking into it and will get back to you ASAP.

@sayanchowdhury Could you reproduce this issue (since you are running on F20)?

I think running waartaa using `mrt` should fix this issue.

**Comment by Pablo2m** [comment] 2014-01-13 17:38
Thanks for your reply, if i run mrt:

[pablo2m@localhost waartaa]$ mrt

Stand back while Meteorite does its thing

Done installing smart packages

Ok, everything's ready. Here comes Meteor!

[[[[[ ~/Escritorio/IRC/waartaa/waartaa ]]]]]

=> Errors prevented startup:

While building the application:
error: no such package: 'router'
error: no such package: 'HTML5-History-API'
error: no such package: 'page-js-ie-support'

=> Your application has errors. Waiting for file change.

Is it possible that I have an incorrect version of meteor ?

**Comment by rtnpro** [comment] 2014-01-14 12:02
Hey @Pablo2m 

It seems that there's some compatibility issue of `meteor-router` with Meteor 0.7. You could try downgrading meteor to 0.6.x (for now). I will come up with a fix for this ASAP.

**Comment by rtnpro** [comment] 2014-02-18 19:39
This is now fixed by replacing `meteor-router` with `iron-router` as dependency.

**Closed as completed by rtnpro** 2014-02-18 19:39 UTC
Labels: bug
